services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: realworld-docker-frontend
    # ports:
    #  - "3000:3000"
    restart: unless-stopped
    command: serve -s build -l 3000
    networks:
      - realworld-docker-network
  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run start
    restart: unless-stopped
    # ports: 
    #  - "3001:3001"
    environment:
      - PORT=3001
  #    - HOST=http://realworld.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002
    depends_on:
      - api_db
      - mailhog # Ensure that MailHog starts before the api service
    networks:
      - realworld-docker-network
  
  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    # ports:
    #  - "3002:3002"
    environment:
      - PORT=3002
   #   - HOST=http://realworld.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001
    depends_on:
      - auth_db
    networks:
      - realworld-docker-network
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - realworld-docker-network
  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - realworld-docker-network
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - realworld-docker-network
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"  # Web interface for viewing sent emails
      - "1025:1025"  # SMTP port for sending emails
    networks:
      - realworld-docker-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  realworld-docker-network:
    driver: bridge

# For the first volume above (mongodb_api), on Windows, the data are saved in the following
# folder (inside the WSL 2 filesystem, that is, in the Linux subfolder) :
# \\wsl.localhost\docker-desktop-data\data\docker\volumes\realworld-docker_mongodb_api
# similar paths are created for all the other volumes